spring:
  application:
    name: congestion-tax-calculator
  profiles:
    default: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-components: always
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        congestion.tax.calculation: true

logging:
  level:
    root: INFO
