CREATE TABLE city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    time_zone VARCHAR(64) NOT NULL,

    CONSTRAINT uk_city_code
        UNIQUE (code),

    CONSTRAINT ck_city_code_not_blank
        CHECK (btrim(code) <> ''),

    CONSTRAINT ck_city_name_not_blank
        CHECK (btrim(name) <> ''),

    CONSTRAINT ck_city_time_zone_not_blank
        CHECK (btrim(time_zone) <> '')
);

CREATE TABLE vehicle_type (
    code VARCHAR(32) PRIMARY KEY,
    description VARCHAR(128) NOT NULL,

    CONSTRAINT ck_vehicle_type_code_not_blank
        CHECK (btrim(code) <> ''),

    CONSTRAINT ck_vehicle_type_description_not_blank
        CHECK (btrim(description) <> '')
);

CREATE TABLE tax_rule_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,

    CONSTRAINT fk_tax_rule_set_city
        FOREIGN KEY (city_id)
        REFERENCES city (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_tax_rule_set_city
        UNIQUE (city_id),

    CONSTRAINT ck_tax_rule_set_currency_code
        CHECK (currency_code ~ '^[A-Z]{3}$')
);

CREATE TABLE tax_rule_option_type (
    code VARCHAR(32) PRIMARY KEY,
    description VARCHAR(128) NOT NULL,

    CONSTRAINT ck_tax_rule_option_type_code_not_blank
        CHECK (btrim(code) <> ''),

    CONSTRAINT ck_tax_rule_option_type_description_not_blank
        CHECK (btrim(description) <> '')
);

CREATE TABLE tax_rule_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_set_id BIGINT NOT NULL,
    type_code VARCHAR(32) NOT NULL,
    amount NUMERIC(12, 2),
    duration_minutes INTEGER,
    preceding_days SMALLINT,
    description VARCHAR(255),

    CONSTRAINT fk_tax_rule_option_rule_set
        FOREIGN KEY (rule_set_id)
        REFERENCES tax_rule_set (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tax_rule_option_type
        FOREIGN KEY (type_code)
        REFERENCES tax_rule_option_type (code)
        ON DELETE RESTRICT,

    CONSTRAINT uk_tax_rule_option_rule_set_type
        UNIQUE (rule_set_id, type_code),

    CONSTRAINT ck_tax_rule_option_value
        CHECK (
            (
                type_code = 'DAILY_MAXIMUM'
                AND amount IS NOT NULL
                AND amount > 0
                AND duration_minutes IS NULL
                AND preceding_days IS NULL
            )
            OR
            (
                type_code = 'CHARGE_WINDOW'
                AND amount IS NULL
                AND duration_minutes IS NOT NULL
                AND duration_minutes > 0
                AND preceding_days IS NULL
            )
            OR
            (
                type_code = 'HOLIDAY_PRECEDING'
                AND amount IS NULL
                AND duration_minutes IS NULL
                AND preceding_days IS NOT NULL
                AND preceding_days > 0
            )
        )
);

CREATE TABLE tax_time_band (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_set_id BIGINT NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_tax_time_band_rule_set
        FOREIGN KEY (rule_set_id)
        REFERENCES tax_rule_set (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_tax_time_band_rule_set_times
        UNIQUE (rule_set_id, start_time, end_time),

    CONSTRAINT ck_tax_time_band_boundaries
        CHECK (end_time <> start_time),

    CONSTRAINT ck_tax_time_band_non_negative_amount
        CHECK (amount >= 0)
);

INSERT INTO tax_rule_option_type (code, description)
VALUES
    ('DAILY_MAXIMUM', 'Maximum Daily Tax amount'),
    ('CHARGE_WINDOW', 'Charge Window duration in minutes'),
    (
        'HOLIDAY_PRECEDING',
        'Number of tax-free dates before a public holiday'
    );
