CREATE TABLE tax_exemption_type (
    code VARCHAR(32) PRIMARY KEY,
    description VARCHAR(128) NOT NULL,

    CONSTRAINT ck_tax_exemption_type_code_not_blank
        CHECK (btrim(code) <> ''),

    CONSTRAINT ck_tax_exemption_type_description_not_blank
        CHECK (btrim(description) <> '')
);

CREATE TABLE tax_exemption (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_set_id BIGINT NOT NULL,
    type_code VARCHAR(32) NOT NULL,
    day_of_week SMALLINT,
    month_number SMALLINT,
    holiday_date DATE,
    vehicle_type_code VARCHAR(32),
    description VARCHAR(255),

    CONSTRAINT fk_tax_exemption_rule_set
        FOREIGN KEY (rule_set_id)
        REFERENCES tax_rule_set (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tax_exemption_type
        FOREIGN KEY (type_code)
        REFERENCES tax_exemption_type (code)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tax_exemption_vehicle_type
        FOREIGN KEY (vehicle_type_code)
        REFERENCES vehicle_type (code)
        ON DELETE RESTRICT,

    CONSTRAINT ck_tax_exemption_value
        CHECK (
            (
                type_code = 'WEEKDAY'
                AND day_of_week IS NOT NULL
                AND day_of_week BETWEEN 1 AND 7
                AND month_number IS NULL
                AND holiday_date IS NULL
                AND vehicle_type_code IS NULL
            )
            OR
            (
                type_code = 'MONTH'
                AND day_of_week IS NULL
                AND month_number IS NOT NULL
                AND month_number BETWEEN 1 AND 12
                AND holiday_date IS NULL
                AND vehicle_type_code IS NULL
            )
            OR
            (
                type_code = 'PUBLIC_HOLIDAY'
                AND day_of_week IS NULL
                AND month_number IS NULL
                AND holiday_date IS NOT NULL
                AND vehicle_type_code IS NULL
            )
            OR
            (
                type_code = 'VEHICLE_TYPE'
                AND day_of_week IS NULL
                AND month_number IS NULL
                AND holiday_date IS NULL
                AND vehicle_type_code IS NOT NULL
            )
        )
);

CREATE UNIQUE INDEX uk_tax_exemption_rule_set_weekday
    ON tax_exemption (rule_set_id, day_of_week)
    WHERE type_code = 'WEEKDAY';

CREATE UNIQUE INDEX uk_tax_exemption_rule_set_month
    ON tax_exemption (rule_set_id, month_number)
    WHERE type_code = 'MONTH';

CREATE UNIQUE INDEX uk_tax_exemption_rule_set_public_holiday
    ON tax_exemption (rule_set_id, holiday_date)
    WHERE type_code = 'PUBLIC_HOLIDAY';

CREATE UNIQUE INDEX uk_tax_exemption_rule_set_vehicle_type
    ON tax_exemption (rule_set_id, vehicle_type_code)
    WHERE type_code = 'VEHICLE_TYPE';

INSERT INTO tax_exemption_type (code, description)
VALUES
    ('WEEKDAY', 'Tax-free day of week'),
    ('MONTH', 'Tax-free month'),
    ('PUBLIC_HOLIDAY', 'Tax-free public holiday'),
    ('VEHICLE_TYPE', 'Tax-free Vehicle Type');
